// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Yu_Gi_Oh_Infrasturcture;

#nullable disable

namespace Yu_Gi_Oh_Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Yu_Gi_Oh_Infrasturcture.Models.CardModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Archetype")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FrameType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("Yu_Gi_Oh_Infrasturcture.Models.MonsterCardModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Attack")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Attribute")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CardId")
                        .HasColumnType("text");

                    b.Property<string>("Defence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string[]>("LinkMarkers")
                        .HasColumnType("text[]");

                    b.Property<string>("LinkValue")
                        .HasColumnType("text");

                    b.Property<string>("Scale")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CardId")
                        .IsUnique();

                    b.ToTable("MonsterCards");
                });

            modelBuilder.Entity("Yu_Gi_Oh_Infrasturcture.Models.MonsterCardModel", b =>
                {
                    b.HasOne("Yu_Gi_Oh_Infrasturcture.Models.CardModel", "Card")
                        .WithOne("MonsterCard")
                        .HasForeignKey("Yu_Gi_Oh_Infrasturcture.Models.MonsterCardModel", "CardId");

                    b.Navigation("Card");
                });

            modelBuilder.Entity("Yu_Gi_Oh_Infrasturcture.Models.CardModel", b =>
                {
                    b.Navigation("MonsterCard");
                });
#pragma warning restore 612, 618
        }
    }
}
